version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:21.3.20.1 
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - ./services/clickhouse/clickhouse_data:/var/lib/clickhouse 
      - ./services/clickhouse/logs:/var/log/clickhouse-server

  data-loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-loader
    command: bash -c "sleep 15 && python3 data_loader.py"
    environment:
      CSV_DIR: /csv_data
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    volumes:
      - ./datasets:/csv_data
      - ./all_schemas.yaml:/app/all_schemas.yaml
      - ./data_loader.py:/app/data_loader.py

  grafana:
    container_name: grafana_test_multicam
    image: grafana/grafana-oss:11.3.4-ubuntu
    environment:
      GF_RENDERER_PLUGIN_TZ: 'GMT'
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_ALLOW_EMBEDDING: "true"
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    restart: unless-stopped
    ports:
      - "3112:3000"
    volumes:
      - ./services/grafana:/var/lib/grafana